name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: yarn start
